DROP TABLE pemesanan;
DROP TABLE pengiriman;
DROP TABLE trolley;
DROP TABLE wishlist;
DROP TABLE foto_produk;
DROP TABLE kurir;
DROP TABLE list_tujuan_pengiriman;
DROP TABLE produk;
DROP TABLE customers;